[package]
name = "oxedyne_fe2o3_tui"
version = "0.5.0"
authors = ["h00gs <hello@oxedyne.io>"]
edition = "2021"
license = "BSD-2-Clause/Apache-2.0"
description = "Hematite text user interface library."
repository = "https://github.com/oxedyne-io/fe2o3"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ironic"
path = "src/main.rs"

[dependencies]
oxedyne_fe2o3_core 		   	= { path = "../fe2o3_core" }
oxedyne_fe2o3_file			= { path = "../fe2o3_file" }
oxedyne_fe2o3_geom 		   	= { path = "../fe2o3_geom" }
oxedyne_fe2o3_hash			= { path = "../fe2o3_hash" }
oxedyne_fe2o3_iop_hash		= { path = "../fe2o3_iop_hash" }
oxedyne_fe2o3_jdat 		   	= { path = "../fe2o3_jdat" }
oxedyne_fe2o3_stds	   		= { path = "../fe2o3_stds" }
oxedyne_fe2o3_syntax	   	= { path = "../fe2o3_syntax" }
oxedyne_fe2o3_text	   		= { path = "../fe2o3_text" }
oxedyne_fe2o3_units	   		= { path = "../fe2o3_units" }

crossterm = "0.27"
secrecy = "0.8.0"

[dev-dependencies]
